name: Deploy Node app to Azure Web App (mockapi)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Instala dependencias en el runner
      - name: Install deps
        run: npm ci --omit=dev

      # Empaquetamos código + node_modules para que Azure no dependa de Oryx
      - name: Prepare artifacts
        run: |
          mkdir build
          cp -r package.json package-lock.json server.js db.json node_modules build/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agrotrack-mockapi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build
          
